### ISSUE TITLE
からあげさんとぴざさんがでないの

### ISSUE THREAD

**Issue by Beryllium17** [TomSuzuki/gacha#1]
からあげさんとピザさんはどこに行ったんですか？

**Comment by TomSuzuki** [comment]
データの最後の食べ物が出ない？ランダムの設定ミスかな…

**Comment by TomSuzuki** [comment]
修正しました！

commit: [f5eb621](https://github.com/TomSuzuki/gacha/commit/f5eb621b671755d0f54aa63f15ac83ad47f7d620)
